<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.materia</groupId>
  <artifactId>MateriaBotLibrary</artifactId>
  <version>2.0.0</version>
  <packaging>jar</packaging>
  <name>MateriaBotLibrary</name>
	<url>https://www.patreon.com/MateriaBot</url>
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<repositories>
		<repository>
			<id>jcenter</id>
		    <name>jcenter-bintray</name>
		    <url>https://jcenter.bintray.com</url>
		</repository>
		<repository>
			<id>jitpack.io</id>
			<url>https://jitpack.io</url>
		</repository>
	</repositories>
	<dependencies>
		<dependency>
		    <groupId>net.dv8tion</groupId>
		    <artifactId>JDA</artifactId>
    		<version>4.1.1_147</version>
		    <exclusions>
		        <exclusion>
		            <groupId>club.minnced</groupId>
		            <artifactId>opus-java</artifactId>
		        </exclusion>
		    </exclusions>
		</dependency>
		<dependency>
		    <groupId>com.jagrosh</groupId>
		    <artifactId>jda-utilities</artifactId>
		    <version>3.0.2</version>
		    <scope>compile</scope>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>8.0.19</version>
		</dependency>
		<dependency>
		    <groupId>org.apache.commons</groupId>
		    <artifactId>commons-lang3</artifactId>
		    <version>3.9</version>
		</dependency>
		<dependency>
			<groupId>com.patreon</groupId>
			<artifactId>patreon</artifactId>
			<version>0.4.2</version>
		</dependency>
		<dependency>
		    <groupId>com.michaelwflaherty</groupId>
		    <artifactId>cleverbotapi</artifactId>
		    <version>1.0.3</version>
		</dependency>
		<dependency>
		  <groupId>com.google.guava</groupId>
		  <artifactId>guava</artifactId>
		  <version>29.0-jre</version>
		</dependency>
	</dependencies>
</project>